### ISSUE TITLE
Stream into ZipArchiveEntry

### ISSUE THREAD

**Issue by chriskinsman** [archiverjs/node-zip-stream#15]
I have a variable amount of data I am reading out of a database in chunks and need to stream to an entry in a zip file.

I see that archive.entry() takes a readable stream potentially as it's first argument however I don't have a stream.  

I am really looking for a way that archive.entry returns a writable stream that I can write my data to incrementally and then close the entry when the stream is closed.

Am I missing a way to do this?

**Comment by chriskinsman** [comment]
Thought I found a way with this code

var Readable = require('stream').Readable;
var stream = new Readable();
archive.entry(stream, {name: 'foo.csv'}, function(err, entry) {
    // Keep ending up here with err set to 'not implemented'
});

**Comment by ctalkington** [comment]
do you have a stack trace?

**Comment by chriskinsman** [comment]
Figured it out.  Had to implement _read() 

Not the easiest way to do this.  Would be really nice if I could get a writable stream from archive.entry() somehow

**Comment by ctalkington** [comment]
its a thought i think tar-stream kinda does the "return writable stream" too but will keep it in mind.
