### ISSUE TITLE
Find out size before piping

### ISSUE THREAD

**Issue by steebchen** [archiverjs/node-zip-stream#18]
Can I get the size of the zip file so I can send a content-length header before piping it to res?
Otherwise, the user doesn't see how big the file is.
Something like that:
	
	async.series(items, function (err, result) {
		archive.finish();

		// I would like to set the content-length header here and then pipe it

		archive
			.pipe(res)
			.on('end', end)
			.on('finish', end);
	});

Is it possible? Or do I really have to write it to disk fs.createReadStream, read the size, and then pipe it to the user?

**Comment by ctalkington** [comment]
streams need to be consumed for flowing to happen so you would need to write to disk and then stream from disk to user.

**Comment by red-0ne** [comment]
But if we know the exact size of each entry, and have a compression level of 0, We should be able to predict the archive size. Does this [stackoverflow](https://stackoverflow.com/questions/10927442/calculate-size-of-zip-file-with-compression-level-0/19380600#19380600) answer apply to `node-zip-stream` or this implementation does things differently ?

**Comment by raghuchahar007** [comment]
@ctalkington If I know the total size of files I am appending in zip-stream than would it be equal to resultant zip or not?
