### ISSUE TITLE
Warning: deflate-crc32-stream@0.1.2: module has been merged into crc32-stream

### ISSUE THREAD

**Issue by fxbenard** [archiverjs/node-zip-stream#19]
I ran into this warning message:

deflate-crc32-stream@0.1.2: module has been merged into crc32-stream

Is it related to your module? If it's the case can you fix this warning.

`-- grunt-contrib-compress@0.8.0
`-- archiver@0.8.1
    `-- zip-stream@0.3.7
`-- deflate-crc32-stream@0.1.2

**Comment by ctalkington** [comment]
this is intentional change that shouldnt be an issue in modern versions of compress.
