### ISSUE TITLE
can't change time by set forceLocalTime

### ISSUE THREAD

**Issue by southnan0** [archiverjs/node-zip-stream#24]
default time is UTC ,I want to change time by local,  I found set forceLocalTime true isn't change!After read the source, I found  ` entry.setTime(data.date)`. In compress-commons ,setTime can recieve 2 params,like that  `ZipArchiveEntry.prototype.setTime = function(time, forceLocalTime)`. I hope you can fix it. Thanks!

**Comment by ghornich** [comment]
I'm having this exact same issue. My timezone is GMT+2 (Budapest, DST). When I create an archive file with 
`forceLocalTime: true`, the resulting file modified date is 2 hours less than my actual computer time.

Reproduced using this code:

    var fs = require('fs');
    var archiver = require('archiver');
    
    var archive = archiver('zip', { forceLocalTime: true });
    
    archive.pipe(fs.createWriteStream('out.zip'));
    archive.append('testfile', { name: 'testfile.txt' });
    archive.finalize();

**Comment by gotoken** [comment]
I hope this issue to be fixed. I'm using a workaround like this: 

```javascript
archive.directory(name, name, (entryData)=>{
  if (archive.options.forceLocalTime) {
    const f = (t)=>{t.setTime(t.getTime-t.getTimezoneOffset()*60000)};
    f(entryData.stats.mtime);
  }
  return entryData;
});
```
