### ISSUE TITLE
Request: Function for pre-calculating size with store only archives

### ISSUE THREAD

**Issue by DanTheMan827** [archiverjs/node-zip-stream#30]
A function to calculate the final size of the archive would be possible if all files were of known sizes and compression was set to STORE.

**Comment by soyuka** [comment]
It's already possible with the high-level api [node-archiver](https://github.com/archiverjs/node-archiver). See [this example](https://github.com/archiverjs/node-archiver/blob/master/examples/progress.js). 

```
archiver.on('progress', () => {})
```

You won't need to pre-calculate the size with STORE and you can use `fs.totalBytes`. Though, it's computed asynchronously as the archive is being built, therefore results might not be exact.

**Comment by DanTheMan827** [comment]
@soyuka That's not quite what I had in mind.

I'm referring to a function that could calculate the final size of the zip with all of the additional data so that the Content-Length header could be set.

**Comment by soyuka** [comment]
Oh, use `archive.pointer()` then it's already computed (in the high-level module, not sure about this one).

**Comment by aaronshaf** [comment]
@soyuka you're reference to `node-archiver` helped me a TON!
