### ISSUE TITLE
some tests broken on node 10

### ISSUE THREAD

**Issue by starpit** [archiverjs/node-zip-stream#34]
e.g. the pack test seems to fail against node 10, but succeeds against node 8

```
     TypeError: Cannot read property 'objectMode' of undefined
      at WriteHashStream.Writable.write (_stream_writable.js:271:22)
```

**Comment by ctalkington** [comment]
seems like it may have resolved itself. not quite sure if it was a bad CI build or what.

**Comment by ctalkington** [comment]
this seems broken on node 10.6.0 but not 10.8.0 so im wondering if its a platform bug
