### ISSUE TITLE
Does not work with streams & AWS S3

### ISSUE THREAD

**Issue by ffxsam** [archiverjs/node-zip-stream#35]
Just pointing out that this library does not work with AWS Lambda & S3 in a full streaming setup. It seems to die in the middle of the read stream and the whole process just quits.

I've had luck with another zip streaming library, though.

**Comment by fjeddy** [comment]
This is highly dependent on your setup, I for one just set it up to zip and transfer 90,732 files in a total of 40GB in a "full streaming setup".

This library has nothing to do with S3 itself, and it's more likely that your code is faulthy / bad, then this being an issue with the library.
