### ISSUE TITLE
macosx random zlib issues

### ISSUE THREAD

**Issue by ctalkington** [archiverjs/node-zip-stream#4]
this has been reported numerous times would be good to figure out whats causing it.

**Comment by remy** [comment]
Can you add any detail about the random issue you're seeing? I've been investigating a problem where I'm running around 500,000 objects through a stream and when it goes to export my stream to a file via the zip-stream, the stream just randomly ends (around 120,000 objects). It doesn't error. It doesn't log anything, just quietly finishes the stream. I'm now wondering, given this issue, if the two things are related.

**Comment by cantidio** [comment]
Hi, I'm using your package and in Mac i'm having some problems. Not as random as the title suggests.
Node 4.0.1 , "zip-stream": "^0.5.2"

I'm just creating a archive with 2 files inside, 2 .txt files that I append like this:

```javascript
zipStream.append(stream1, {
    name: 'file1.txt'
  }).append(stream2, {
    name: 'file2.txt'
  }).finalize();
```

I can make it work when the txt files are somewhat around 1000 lines, but when I try something larger than the zip file generated is not valid.

Getting this:
```
Archive:  lists.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of lists.zip or
        lists.zip.zip, and cannot find lists.zip.ZIP, period.
```

Any Idea how to solve this?

Thanks in advance.

**Comment by ctalkington** [comment]
@cantidio this is because zip-stream doesn't handle queue on its own. you would need to nest callbacks or setup some async helper.

**Comment by cantidio** [comment]
Hello @ctalkington actually I tested with only one big file and with nested callbacks as well.
I got the same results unfortunately. 
So I was playing with the options and I found out that when I used the  store: false in the options it works on Mac for no reason at all. 
I'm really confused with this.

**Comment by ctalkington** [comment]
as there have been a lot of changes to node over the years and we moving support away from pre v4 versions. Let's close this and keep track of anything still arises.
